// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Bos Computing LLC

import { defineConfig } from "@playwright/test";

/**
 * Playwright configuration for visual regression testing.
 *
 * Separate from the functional E2E config (playwright.config.ts) because:
 * - No API server needed (all API calls are mocked in fixtures)
 * - Different viewport projects (mobile / tablet / desktop)
 * - snapshotPathTemplate for organized screenshot storage
 *
 * Run:
 *   pnpm --filter @eco/web test:visual
 *   pnpm --filter @eco/web test:visual:update
 */
export default defineConfig({
  testDir: "./e2e/visual",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 2 : undefined,
  reporter: process.env.CI
    ? [["github"], ["html", { open: "never" }]]
    : "html",
  // 60s per test. Cold Next.js dev server compilation on CI containers
  // takes 20-30s for the first page hit; 30s leaves no margin and
  // produces false-positive `page.goto: Test timeout` failures.
  timeout: 60_000,

  snapshotPathTemplate:
    "{testDir}/__screenshots__/{projectName}/{arg}{ext}",

  expect: {
    toHaveScreenshot: {
      // 0.02 absorbs sub-pixel anti-alias / font-subpixel variance that
      // can exist even between two runs of the same Ubuntu Playwright
      // container — the baselines are now generated by the same image
      // that validates them (.github/workflows/visual-baseline-regen.yml).
      // 0.001 was unachievable in practice; 0.02 still catches anything
      // larger than 2% of pixels — well within real-visual-change range.
      maxDiffPixelRatio: 0.02,
      animations: "disabled",
      caret: "hide",
      scale: "css",
    },
  },

  use: {
    baseURL: "http://localhost:3000",
    trace: "on-first-retry",
  },

  projects: [
    {
      name: "mobile",
      testIgnore: /dark-mode\.spec\.ts/,
      use: {
        viewport: { width: 375, height: 812 },
        deviceScaleFactor: 2,
        isMobile: true,
        hasTouch: true,
      },
    },
    {
      name: "tablet",
      testIgnore: /dark-mode\.spec\.ts/,
      use: {
        viewport: { width: 768, height: 1024 },
        deviceScaleFactor: 2,
      },
    },
    {
      name: "desktop",
      use: {
        viewport: { width: 1440, height: 900 },
        deviceScaleFactor: 1,
      },
    },
  ],

  webServer: {
    command: "pnpm --filter @eco/web dev",
    url: "http://localhost:3000",
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
  },
});
